name: Pull Request Labeler

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:
    inputs:
      pr_number:
        description: Pull request number to label
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    if: >-
      github.repository == 'omkar-334/warehouse' &&
      (
        github.event_name == 'workflow_dispatch' ||
        github.event.pull_request.head.repo.full_name == github.repository
      )
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          pr-number: ${{ github.event.inputs.pr_number || github.event.pull_request.number }}
